### ISSUE TITLE
'kthLargestElement' modifies the input array

### ISSUE THREAD

**Issue by Abhilash3** [jattdaljit/Data-Structures#1]
Modifying the input is a bit of the problem.
Its possible to implement this in O(n) and without modifying the original array.
Feel free to use extra memory if you this its required.

**Comment by jattdaljit** [comment]
I am not able to find the solution in O(n) time complexity. Can you help !!

**Comment by Abhilash3** [comment]
Think about how would you find max in an array.
You use 'max' variable to keep the max value and iterate over an array.
For kth max; you can use k separate variables to track values and return the minimum in them.

**Comment by jattdaljit** [comment]
this would also lead to O(n2) complexity

**Comment by Abhilash3** [comment]
it would be O(n * k); if u think its bad; think linkedlist

**Comment by jattdaljit** [comment]
Modified the code using extra array of size k - Time complexity O(n*k)
