### ISSUE TITLE
'findMaxInArrayUsingRecursion' can give invalid value

### ISSUE THREAD

**Issue by Abhilash3** [jattdaljit/Data-Structures#2]
findMaxInArrayUsingRecursion function public implementation allows an int parameter and will only check ahead of it; which can be broken with something like:
`int[] a = {79, 3, 5, 1, 6};`
`System.out.println(findMax(a, 1));`

A function with a parameter which is not an input, should not have public access.
Update the implementation to provide a public function without such parameter.

**Comment by jattdaljit** [comment]
Modified the code as per requirements

**Comment by Abhilash3** [comment]
Normally its me who should close it, after checking and confirming the code.

**Comment by jattdaljit** [comment]
It was by mistake I clicked on close and comment.
